<?php

/**
 * @file
 * Blog Entity Example module.
 */

// Include the declarations for the blogEntity and controller classes
module_load_include('inc', 'blog_entity', 'includes/blog_entity.class');

 /**
 * Implements hook_entity_info().
 */
function blog_entity_entity_info() {
  $return = array(
    'blog_entity' => array(
      'label' => t('Blog Entity'),
      'plural label' => t('Blog Entities'),
      'description' => t('An entity type for creating blog posts'),
      'entity class' => 'BlogEntity',
      'controller class' => 'BlogEntityController',
      'base table' => 'blog_entity',
      'entity keys' => array(
        'id' => 'bid',
        'label' => 'title',
      ),
      'uri callback' => 'entity_class_uri',
      'module' => 'blog_entity',
      'admin ui' => array(
        'path' => 'admin/content/blog-entity',
        'file' => 'includes/blog_entity.admin_ui.inc',
      ),
      'access callback' => 'blog_entity_access_callback',
      'fieldable' => TRUE,
      'bundles' => array(
        'blog_entiy' => array(
          'label' => 'Blog Entity',
          'admin' => array(
            'path' => 'admin/structure/blog-entity',
            'access arguments' => array('administer site configuration'),
          ),
        ),
      ),
    ),
  );

  return $return;
}

/**
 * Implements hook_menu().
 */
function blog_entity_menu() {
  $items = array();

  // Create a stub page for configuring the blog entity
  $items['admin/structure/blog-entity'] = array(
    'title' => 'Blog Entity',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'blog_entity_page_callback',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback referenced in blog_entity_menu that creates a stub page for the structure menu
 */
function blog_entity_page_callback() {
  drupal_set_message("The blog entity only supports a single bundle right now.");
  return "";
}

/**
 * Access callback set in blog_entity_entity_info
 */
function blog_entity_access_callback($op, $entity, $account, $entity_type) {
    return TRUE;
}
