<?php

/**
 * @file
 * Blog Entity Example module.
 */

 /**
 * Implements hook_entity_info().
 */
function blog_entity_entity_info() {
  $return = array(
    'blog_entity' => array(
      'label' => t('Blog Entity'),
      'plural label' => t('Blog Entities'),
      'description' => t('An entity type for creating blog posts'),
      'entity class' => 'BlogEntity',
      'controller class' => 'BlogEntityController',
      'base table' => 'blog_entity',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'bid',
        'label' => 'title',
      ),
      'uri callback' => 'entity_class_uri',
      'module' => 'blog_entity',
    ),
  );

  return $return;
}

/**
 * Define a custom entity class.
 */
class BlogEntity extends Entity {

  /**
   * Overrides defaultUri() to implement a custom default URI
   */
  protected function defaultUri() {
    return array('path' => 'blog/' . $this->identifier());
  }

}

/**
 * Define a custom entity controller class.
 */
class BlogEntityController extends EntityAPIController {

}